### PR TITLE
check now finishes with some issues

### PR DESCRIPTION
**Pull request by andrewelamb**

### CODE REVIEW

**Comment by andrewelamb** [comment]
Hey @allaway:

I commented out this function call in the vignette:
````
library(survival)
goldStandard <- Surv(d.time, death) %>% as.character() %>% as.data.frame() %>% magrittr::set_colnames(c("gold"))
predictions <- age_new %>% as.data.frame() %>% magrittr::set_colnames(c("pred"))
prevPredictions <- age_previous %>% as.data.frame() %>% magrittr::set_colnames(c("pred"))

# TODO: fix this error: Error: `by` required, because the data sources have no common variables
# bootLadderBoot(predictions = predictions,
#                predictionColname = "pred", 
#                prevPredictions = prevPredictions,
#                goldStandard = goldStandard,
#                goldStandardColname = "gold",
#                scoreFun = c_statistic,
#                verbose = T)
````
To get check() to work. The error is not super helpful in this context(this could indicate some error handling could be added to this function).

**Comment by thomasyu888** [comment]
What is 'check now'?  Can you add a brief description?

**Comment by andrewelamb** [comment]
Oh yes check() is a function that goes through a package and does several things like run the tests, make sure the documentation is correct, runs the vignettes, etc...

**Comment by allaway** [comment]
IIRC the ability to run this function on Surv objects was never finished. This is related to #11

**Pull request merged**
